/**
 * 常量定义
 */
export default class CommonConstants {
  /**
   * width: 100%
   */
  static readonly FULL_WIDTH: string = '100%'
  /**
   * height: 100%
   */
  static readonly FULL_HEIGHT: string = '100%'
  /**
   * slider最小值: 0
   */
  static readonly SLIDER_MIN_VALUE: number = 0;
  /**
   * slider最大值: 100
   */
  static readonly SLIDER_MAX_VALUE: number = 100;
  /**
   * slider步长: 1
   */
  static readonly SLIDER_STEP: number = 1;
  /**
   * 透明度: 0.6
   */
  static readonly OPACITY: number = 0.6;
  /**
   * 透明度: 1.0
   */
  static readonly NO_OPACITY: number = 1;
}